FROM alpine:latest

ENV LANG en_US.utf8
EXPOSE 3000

RUN apk add --no-cache bash postgresql-client postgresql-dev gmp

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["-h"]

COPY postgrest /usr/local/bin/
COPY postgrest_available_options.md5 /
RUN postgrest -h > postgrest_usage.txt; \
    sed -n '/Available options/,$p' postgrest_usage.txt > postgrest_available_options; \
    md5sum -c postgrest_available_options.md5 || \
    { echo; echo "WARNING: postgrest available options have changed."; \
      echo "Update the docker-entrypoint.sh to match."; echo; exit 1; }; \
    rm postgrest_available_options*
